name: vulnerable-c-and-cpp

on:
  push:
  workflow_dispatch:

permissions:
  actions: read           # for detecting the Github Actions environment
  id-token: write         # for creating OIDC tokens for signing
  packages: write         # for uploading attestations
  contents: read          # read the contents permission
  security-events: write  # for uploading code scanning

jobs:
  build:
    name: 'Build program1.app'
    env:
      JFROG_CLI_BUILD_NAME: 'program1.app'
      JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}
      JFROG_CLI_BUILD_PROJECT: ${{ vars.JF_PROJECT }}
      JFROG_CLI_LOG_LEVEL: INFO
      DOCKER_REPO: mikeho-github-docker-local
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-cli
        env:
          JF_URL: https://${{ vars.JF_URL }}/
        with:
          oidc-provider-name: mikeho-github
          oidc-audience: mikeho-audience
          version: 2.77.0
          disable-auto-build-publish: true

      - name: Docker Authenticate
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.JF_URL }}
          username: ${{ steps.setup-cli.outputs.oidc-user }}
          password: ${{ steps.setup-cli.outputs.oidc-token }}

      - name: Build program1.app
        run: |
          docker run --rm -v $(pwd):/src -w /src gcc:12.5.0 /bin/bash -c "gcc program1.c -o program1.app"

      - name: Upload program1.app
        run: |
          jf rt u ./program1.app mikeho-vul-c-and-cpp-conan-local/program1/

  publish:
    name: 'Build program2.app'
    env:
      JFROG_CLI_BUILD_NAME: 'program2.app'
      JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}
      JFROG_CLI_BUILD_PROJECT: ${{ vars.JF_PROJECT }}
      JFROG_CLI_LOG_LEVEL: INFO
      DOCKER_REPO: mikeho-github-docker-local
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ vars.JF_URL }}/
        with:
          oidc-provider-name: mikeho-github
          oidc-audience: mikeho-audience
          version: 2.77.0
          disable-auto-build-publish: true

      - name: Download program1.app
        run: |
          jf rt dl mikeho-vul-c-and-cpp-conan-local/program1/program1.app ./

      - name: Build program2.app
        run: |
          docker run --rm -v $(pwd):/src -w /src gcc:12.5.0 /bin/bash -c "gcc program2.c -o program2.app"

      - name: Upload program2.app
        run: |
          jf rt u ./program2.app mikeho-vul-c-and-cpp-conan-local/program2/

      - name: Publish Build with Dependency
        run: |
          jf rt build-collect-env 
          jf rt build-add-git 
          jf rt build-publish 

      - name: Xray Build Security Scan
        run: |            
          jf build-scan --fail=false --vuln
          
